{
  "openapi": "3.1.0",
  "info": {
    "version": "6.0.4",
    "title": "Bible SuperSearch API Documentation",
    "contact": {
      "name": "AIC Web Tech",
      "url": "https://aicwebtech.com/"
    },
    "license": {
      "name": "GNU GPL v3.0",
      "url": "https://github.com/seiji-alyosha/bss_api_docs?tab=GPL-.0-1-ov-file.com"
    }
  },
  "servers": [
    {
      "url": "https://api.biblesupersearch.com",
      "description": "Bible SuperSearch API"
    }
  ],
  "externalDocs": {
    "description": "To install the API on your website, click here.",
    "url": "https://www.biblesupersearch.com/downloads"
  },
  "paths": {
    "/api": {
      "get": {
        "summary": "Query",
        "description": "For all queries of Bible information in our database.",
        "parameters": [
          {
            "$ref": "#/components/parameters/reference"
          },
          {
            "$ref": "#/components/parameters/search"
          },
          {
            "$ref": "#/components/parameters/request"
          },
          {
            "$ref": "#/components/parameters/data_format"
          },
          {
            "$ref": "#/components/parameters/bible"
          },
          {
            "$ref": "#/components/parameters/whole_words"
          },
          {
            "$ref": "#/components/parameters/exact_case"
          },
          {
            "$ref": "#/components/parameters/highlight"
          },
          {
            "$ref": "#/components/parameters/highlight_tag"
          },
          {
            "$ref": "#/components/parameters/page"
          },
          {
            "$ref": "#/components/parameters/page_limit"
          },
          {
            "$ref": "#/components/parameters/page_all"
          },
          {
            "$ref": "#/components/parameters/context"
          },
          {
            "$ref": "#/components/parameters/context_range"
          },
          {
            "$ref": "#/components/parameters/search_type"
          },
          {
            "$ref": "#/components/parameters/keyword_limit"
          },
          {
            "$ref": "#/components/parameters/proximity_limit"
          },
          {
            "$ref": "#/components/parameters/markup"
          },
          {
            "$ref": "#/components/parameters/parallel_search_error_suppress"
          },
          {
            "$ref": "#/components/parameters/callback"
          }
        ],
        "examples": {
          "reference_url": {
            "summary": "Get a Bible pasasage",
            "value": {
              "reference": "john3:16"
            }
          }
        },
        "responses": {
          "200": {
            "$ref": "#/components/responses/Success"
          },
          "400": {
            "$ref": "#/components/responses/Problem"
          }
        },
        "security": null
      }
    }
  },
  "components": {
    "parameters": {
      "reference": {
        "name": "reference",
        "in": "query",
        "required": false,
        "description": "To find a passage reference (i.e. Psalm63:1-2).",
        "schema": {
          "type": "string",
          "default": "(none)"
        }
      },
      "search": {
        "name": "search",
        "in": "query",
        "required": false,
        "description": "To look for verses with specific words (i.e. love, joy, peace).",
        "schema": {
          "type": "string",
          "default": "(none)"
        }
      },
      "request": {
        "name": "request",
        "in": "query",
        "required": false,
        "description": "Receives keywords or bible references. Cannot receive both. If a passage is used, the `200` response is the same as the response when using the `reference` parameter. If a keyword is used, the response format is the same as the response when using the `search` parameter.",
        "schema": {
          "type": "string",
          "default": "(none)"
        }
      },
      "data_format": {
        "name": "data_format",
        "in": "query",
        "required": false,
        "description": "Formats the structure of the endpoint response. Parameter values can either be:\n- **Passage** - For more informative responses\n- **Raw / minimal** - For more concise responses",
        "schema": {
          "type": "string",
          "default": "passage"
        }
      },
      "bible": {
        "name": "bible",
        "in": "query",
        "description": "Translation of the bible. Can be a string, array, or JSON encoded array.",
        "schema": {
          "type": "string",
          "default": "kjv"
        }
      },
      "whole_words": {
        "name": "whole_words",
        "in": "query",
        "required": false,
        "description": "Sets the search and keyword parameters to search for whole words.",
        "schema": {
          "type": "boolean",
          "default": false
        }
      },
      "exact_case": {
        "name": "exact_case",
        "in": "query",
        "description": "Sets the search and keyword parameters to search for exact case.",
        "schema": {
          "type": "boolean",
          "default": false
        }
      },
      "highlight": {
        "name": "highlight",
        "in": "query",
        "description": "Setting to true will wrap the highlight tag around the keyword.",
        "schema": {
          "type": "string",
          "default": false
        }
      },
      "highlight_tag": {
        "name": "highlight_tag",
        "in": "query",
        "description": "The HTML tag used to highlight keywords.",
        "schema": {
          "type": "string",
          "default": "b"
        }
      },
      "page": {
        "name": "page",
        "in": "query",
        "description": "The number of the page to show.",
        "schema": {
          "type": "string",
          "default": 1
        }
      },
      "page_limit": {
        "name": "page_limit",
        "in": "query",
        "description": "The results per page.",
        "schema": {
          "type": "integer",
          "default": 1
        }
      },
      "page_all": {
        "name": "page_all",
        "in": "query",
        "description": "Shows all results.",
        "schema": {
          "type": "boolean",
          "default": false
        }
      },
      "context": {
        "name": "context",
        "in": "query",
        "description": "Shows the verses surrounding the given verse.",
        "schema": {
          "type": "boolean",
          "default": false
        }
      },
      "context_range": {
        "name": "context_range",
        "in": "query",
        "description": "The amount of verses pulled by the context parameter.",
        "schema": {
          "type": "integer",
          "default": 5
        }
      },
      "search_type": {
        "name": "search_type",
        "in": "query",
        "description": "The type of search when using the keyword search. 'and' or 'all_words' - searches for verses with the given words. 'or' or 'any_word'  - seaches for verses mentioning at least one of the given words. 'xor' or 'one_word' - searches for verses with one of the given words. two_or_more' - searches for verses with two or more of the given words.'",
        "schema": {
          "type": "string",
          "default": "and"
        }
      },
      "keyword_limit": {
        "name": "keyword_limit",
        "in": "query",
        "description": "Sets the minimum amount of keywords for keyword searches.",
        "schema": {
          "type": "integer",
          "default": 5
        }
      },
      "proximity_limit": {
        "name": "proximity_limit",
        "in": "query",
        "description": "Sets the range of verses of allowable verses between keywords. Default is 5.",
        "schema": {
          "type": "integer",
          "default": 5
        }
      },
      "markup": {
        "name": "markup",
        "in": "query",
        "description": "Formats the markup for Strongs numbers or red letters. 'None', or 'raw'. 'raw' returns the markup as stored in the database. {} = srongs numbers, [] = added words, ‹› = red letters (not <>). Default is 5.",
        "schema": {
          "type": "string",
          "default": "none"
        }
      },
      "parallel_search_error_suppress": {
        "name": "parallel_search_error_suppress",
        "in": "query",
        "description": "The 'verses from this Bible have been included for comparison' errors won't show.",
        "schema": {
          "type": "boolean",
          "default": false
        }
      },
      "callback": {
        "name": "callback",
        "in": "query",
        "description": "Name of callback for JSONP.",
        "schema": {
          "type": "string",
          "default": "(none)"
        }
      }
    },
    "schemas": {
      "verse_index_chapter": {
        "title": "Verse index chapter",
        "type": "array",
        "description": "The verse numbers for the given chapter in the search. The verses are in integer format.",
        "example": "\"63\": [ 1, 2, 3 ]"
      },
      "verse": {
        "title": "verse",
        "type": "object",
        "description": "Information for a given verse.",
        "properties": {
          "id": {
            "type": "integer",
            "description": "The verse id.",
            "example": 14845
          },
          "book": {
            "type": "integer",
            "description": "The book id.",
            "example": 19
          },
          "chapter": {
            "type": "integer",
            "description": "The chapter number.",
            "example": 63
          },
          "verse": {
            "type": "integer",
            "description": "The verse number.",
            "example": 5
          },
          "text": {
            "type": "string",
            "description": "The contents of the verse.",
            "example": "My soul shall be satisfied as with marrow and fatness; and my mouth shall praise thee with joyful lips:"
          },
          "italics": {
            "type": "string",
            "description": "(in-progress)"
          },
          "claimed": {
            "type": "boolean",
            "description": "(in-progress)"
          }
        }
      },
      "chapter_verse": {
        "type": "object",
        "title": "Chapter verses",
        "description": "A verse object that contains information about a single verse. Chapter verses are numbers in the form of a string.",
        "additionalProperties": {
          "$ref": "#/components/schemas/verse"
        },
        "example": {
          "5": {
            "id": 14845,
            "book": 19,
            "chapter": 63,
            "verse": 5,
            "text": "My soul shall be satisfied as with marrow and fatness; and my mouth shall praise thee with joyful lips:",
            "italics": "",
            "claimed": true
          }
        }
      },
      "translation_chapter": {
        "type": "object",
        "title": "Translation chapter",
        "description": "A chapter object for a given translation. Each chapter object contains a verse object. Chapter objects are numbers in the form of a string.",
        "additionalProperties": {
          "$ref": "#/components/schemas/chapter_verse"
        },
        "example": {
          "63": {
            "5": {
              "id": 14845,
              "book": 19,
              "chapter": 63,
              "verse": 5,
              "text": "My soul shall be satisfied as with marrow and fatness; and my mouth shall praise thee with joyful lips:",
              "italics": "",
              "claimed": true
            }
          }
        }
      },
      "nav": {
        "title": "nav",
        "type": "object",
        "description": "Contains metadata for navigating multiple verses. Only applicable when searching for multiple verses.",
        "properties": {
          "prev_book": {
            "type": "string",
            "description": "The previous book."
          },
          "next_book": {
            "type": "string",
            "description": "The next book."
          },
          "next_chapter": {
            "type": "string",
            "description": "For the next chapter."
          },
          "ncb_name": {
            "type": "string",
            "description": "Next chapter book name. For the name of the ncb."
          },
          "prev_chapter": {
            "type": "string",
            "description": "For the previous chapter of the book."
          },
          "pcb_name": {
            "type": "string",
            "description": "Previous chapter book name. For the name of the pcb."
          },
          "cur_chapter": {
            "type": "string",
            "description": "For the name of the current chapter of the book."
          },
          "ccb_name": {
            "type": "string",
            "description": "Current chapter book name. Used for the name of the ccb."
          },
          "ncb": {
            "type": "integer",
            "description": "Next chapter book id. Used to identify the book of the next chapter of the search entry."
          },
          "ncc": {
            "type": "integer",
            "description": "Next chapter chapter id. Used to identify the chapter for the next chapter of the search entry."
          },
          "pcb": {
            "type": "integer",
            "description": "Previous chapter book id. Used to identify the book for the previous chapter of the search entry."
          },
          "pcc": {
            "type": "integer",
            "description": "Previous chapter chapter id. Used to identify the chapter for the previous chapter of the search entry."
          },
          "ccb": {
            "type": "integer",
            "description": "Current chapter book id. Used to identify the book of the search entry."
          },
          "ccc": {
            "type": "integer",
            "description": "Current chapter chapter id. Used to identify the chapter of the search entry."
          },
          "nb": {
            "type": "integer",
            "description": "Book id for the next book."
          },
          "pb": {
            "type": "integer",
            "description": "Book id for the previous book."
          }
        },
        "example": "'nav': { 'prev_book': 'Job', 'next_book': 'Proverbs', 'next_chapter': 'Psalms 64', 'ncb_name': 'Psalms', 'prev_chapter': 'Psalms 62', 'pcb_name': 'Psalms', 'cur_chapter': 'Psalms 63', 'ccb_name': 'Psalms', 'ncb': 19, 'ncc': 64, 'pcb': 19, 'pcc': 62, 'ccb': 19, 'ccc': 63, 'nb': 20, 'pb': 18, }"
      },
      "query_results_passage": {
        "type": "object",
        "description": "Lists information about the books, chapters, and verses related to the parameter details in the request. Returns results based on the `data_format`, which determines the structure of the results.",
        "properties": {
          "book_id": {
            "type": "integer",
            "description": "The ID of the book.",
            "example": 19
          },
          "book_name": {
            "type": "string",
            "description": "The name of the book.",
            "example": "Psalms"
          },
          "book_short": {
            "type": "string",
            "description": "A shortened name for the book.",
            "example": "Ps"
          },
          "book_raw": {
            "type": "string",
            "description": "The name entered by the user for the name of the book.",
            "example": "Psa"
          },
          "chapter_verse": {
            "type": "string",
            "description": "The chapter and verse.",
            "example": "63:1"
          },
          "chapter_verse_raw": {
            "type": "string",
            "description": "The chapter and verse entered by the user.",
            "example": "63:1"
          },
          "verse_index": {
            "type": "object",
            "description": "Contains arrays of each chapter in the search.",
            "additionalProperties": {
              "$ref": "#/components/schemas/verse_index_chapter"
            },
            "example": "'verse_index': { '63': [ 1 ] }"
          },
          "verses": {
            "type": "object",
            "description": "Details about the searched verses in passage format.",
            "additionalProperties": {
              "$ref": "#/components/schemas/translation_chapter"
            },
            "example": {
              "kjv": {
                "63": [
                  1
                ]
              }
            }
          },
          "verses_count": {
            "type": "integer",
            "description": "The amount of verses searched for.",
            "example": 1
          },
          "single_verse": {
            "type": "boolean",
            "description": "Shows if the user searched for one verse or not.",
            "example": true
          },
          "nav": {
            "$ref": "#/components/schemas/nav"
          }
        }
      },
      "translation_verse": {
        "title": "Translation verse",
        "type": "array",
        "description": "When using the 'raw' data format, the results object displays verse information for a given translation. This differs from the 'passage' format, which gives a chapter object and a verse object that holds the verse information. The results object for 'raw' searches only display arrays of verse information for the translation specified in the search.",
        "items": {
          "$ref": "#/components/schemas/verse"
        },
        "example": [
          {
            "id": 14845,
            "book": 19,
            "chapter": 63,
            "verse": 5,
            "text": "My soul shall be satisfied as with marrow and fatness; and my mouth shall praise thee with joyful lips:",
            "italics": "",
            "claimed": true
          }
        ]
      },
      "query_results_raw": {
        "type": "object",
        "description": "Lists verse information based on the parameter details in the request. Returns results based on the `data_format`, which determines the structure of the results.",
        "additionalProperties": {
          "$ref": "#/components/schemas/translation_verse"
        }
      },
      "query": {
        "type": "object",
        "title": "Query response schema",
        "description": "The response schema for the query endpoint.",
        "properties": {
          "hash": {
            "type": "string",
            "description": "A hash code for the endpoint."
          },
          "disambiguation": {
            "type": "array",
            "description": "The purpose of this object is still under investigation."
          },
          "strongs": {
            "type": "array",
            "description": "The contents of this object is unclear. The Strong's definitions endpoint (https://api.biblesupersearch.com/api/strongs) returns Strong's definitions, but this doesn't seem to connected to this object."
          },
          "paging": {
            "type": "object",
            "description": "Returns objects that contain information about the pages of the results. Information such as - Current page of results - URL for the first page - The search result that starts on the current page - The page number of the last page of results - URL for the last page - URLs for all pages of results - URL path for the endpoint - Search results per page - The number of search results for the current page - Total number of search results"
          },
          "errors": {
            "type": "array",
            "description": "If errors occur during the request, this array displays messages about the errors."
          },
          "error_level": {
            "type": "integer",
            "description": "Indicates the type of error that occurred: \n  - **0** - no error\n  - **1** or **2** - reserved for future use\n  - **3** - non-fatal error\n  - **4** - fatal error"
          },
          "results": {
            "description": "Search results and/or Biblical passages based on the information provided in the request. The structure depends on the `data_format` parameter.\n- **passage** (default) - Returns verse data, along with additional information about the book and chapter. When you do not provide a `data_format`, this is the format of the results object.\n- **raw** - Returns verse data and less information about books and chapters.",
            "oneOf": [
              {
                "type": "array",
                "title": "passage",
                "items": {
                  "$ref": "#/components/schemas/query_results_passage"
                }
              },
              {
                "type": "object",
                "title": "raw",
                "$ref": "#/components/schemas/query_results_raw"
              }
            ]
          }
        }
      },
      "error": {
        "type": "object",
        "title": "error",
        "description": "The response schema for a 400 error.",
        "properties": {
          "hash": {
            "type": "string",
            "description": "A hash code for the endpoint."
          },
          "disambiguation": {
            "type": "array",
            "description": "The purpose of this object is still under investigation."
          },
          "errors": {
            "type": "array",
            "description": "If errors occur during the request, this array displays messages about the errors."
          },
          "error_level": {
            "type": "integer",
            "description": "Indicates the type of error that occurred: \n  - **0** - no error\n  - **1** or **2** - reserved for future use\n  - **3** - non-fatal error\n  - **4** - fatal error"
          },
          "results": {
            "type": "boolean",
            "description": "Displays as \"false\"."
          }
        }
      }
    },
    "responses": {
      "Success": {
        "description": "Successful",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/query"
            },
            "examples": {
              "reference_passage": {
                "summary": "Reference (passage)",
                "description": "Response for a reference query in a **passage** `data_format` (e.g. Psalms63:1-2).",
                "value": {
                  "hash": "pgvu7cuok3",
                  "disambiguation": [],
                  "strongs": [],
                  "paging": [],
                  "errors": [],
                  "error_level": 0,
                  "results": [
                    {
                      "book_id": 19,
                      "book_name": "Psalms",
                      "book_short": "Ps",
                      "book_raw": "Psalm",
                      "chapter_verse": "63:1 - 2",
                      "chapter_verse_raw": null,
                      "verse_index": {
                        "63": [
                          1,
                          2
                        ]
                      },
                      "verses": {
                        "kjv": {
                          "63": {
                            "1": {
                              "id": 14841,
                              "book": 19,
                              "chapter": 63,
                              "verse": 1,
                              "text": "¶ A Psalm of David, when he was in the wilderness of Judah. O God, thou art my God; early will I seek thee: my soul thirsteth for thee, my flesh longeth for thee in a dry and thirsty land, where no water is;",
                              "italics": "",
                              "claimed": true
                            },
                            "2": {
                              "id": 14842,
                              "book": 19,
                              "chapter": 63,
                              "verse": 2,
                              "text": "To see thy power and thy glory, so as I have seen thee in the sanctuary.",
                              "italics": "",
                              "claimed": true
                            }
                          }
                        }
                      },
                      "verses_count": 2,
                      "single_verse": false,
                      "nav": {
                        "prev_book": "Job",
                        "next_book": "Proverbs",
                        "next_chapter": "Psalms 64",
                        "ncb_name": "Psalms",
                        "prev_chapter": "Psalms 62",
                        "pcb_name": "Psalms",
                        "curr_chapter": "Psalms 63",
                        "ccb_name": "Psalms",
                        "ncb": 19,
                        "ncc": 64,
                        "pcb": 19,
                        "pcc": 62,
                        "ccb": 19,
                        "ccc": 63,
                        "nb": 20,
                        "pb": 18
                      }
                    }
                  ]
                }
              },
              "reference_raw": {
                "summary": "Reference (raw)",
                "description": "Response for a reference query in a **raw** `data_format` (e.g. Psalms63:1-2).",
                "value": {
                  "hash": "pgvu7cuok3",
                  "disambiguation": [],
                  "strongs": [],
                  "paging": [],
                  "errors": [],
                  "error_level": 0,
                  "results": {
                    "kjv": [
                      {
                        "id": 14841,
                        "book": 19,
                        "chapter": 63,
                        "verse": 1,
                        "text": "¶ A Psalm of David, when he was in the wilderness of Judah. O God, thou art my God; early will I seek thee: my soul thirsteth for thee, my flesh longeth for thee in a dry and thirsty land, where no water is;",
                        "italics": "",
                        "claimed": true
                      },
                      {
                        "id": 14842,
                        "book": 19,
                        "chapter": 63,
                        "verse": 2,
                        "text": "To see thy power and thy glory, so as I have seen thee in the sanctuary.",
                        "italics": "",
                        "claimed": true
                      }
                    ]
                  }
                }
              },
              "search_passage": {
                "summary": "Search (passage)",
                "description": "Response for a search query in a **passage** `data_format` (e.g. Peace).",
                "value": {
                  "hash": "573us0u6sh",
                  "disambiguation": [],
                  "strongs": [],
                  "paging": {
                    "current_page": 1,
                    "first_page_url": "https://api.biblesupersearch.com/api?page=1",
                    "from": 1,
                    "last_page": 14,
                    "last_page_url": "https://api.biblesupersearch.com/api?page=14",
                    "links": [
                      {
                        "url": null,
                        "label": "&laquo; Previous",
                        "active": false
                      },
                      {
                        "url": "https://api.biblesupersearch.com/api?page=1",
                        "label": "1",
                        "active": true
                      },
                      {
                        "url": null,
                        "label": "...",
                        "active": false
                      },
                      {
                        "url": "https://api.biblesupersearch.com/api?page=2",
                        "label": "Next &raquo;",
                        "active": false
                      }
                    ],
                    "path": "https://api.biblesupersearch.com/api",
                    "per_page": 30,
                    "to": 30,
                    "total": 420
                  },
                  "errors": [],
                  "error_level": 0,
                  "results": [
                    {
                      "book_id": 1,
                      "book_name": "Genesis",
                      "book_short": "gen",
                      "book_raw": null,
                      "chapter_verse": "15:15",
                      "chapter_verse_raw": "15:15",
                      "verse_index": {
                        "15": [
                          15
                        ]
                      },
                      "verses": {
                        "kjv": {
                          "15": {
                            "15": {
                              "id": 376,
                              "book": 1,
                              "chapter": 15,
                              "verse": 15,
                              "text": "And thou shalt go to thy fathers in peace; thou shalt be buried in a good old age.",
                              "italics": "",
                              "claimed": true
                            }
                          }
                        }
                      },
                      "verses_count": 1,
                      "single_verse": true,
                      "nav": []
                    }
                  ]
                }
              },
              "search_raw": {
                "summary": "Search (raw)",
                "description": "Response for a search query in a **raw** `data_format` (e.g. Peace).",
                "value": {
                  "hash": "owbc87niaf",
                  "disambiguation": [],
                  "strongs": [],
                  "paging": {
                    "current_page": 1,
                    "first_page_url": "https://api.biblesupersearch.com/api?page=1",
                    "from": 1,
                    "last_page": 14,
                    "last_page_url": "https://api.biblesupersearch.com/api?page=14",
                    "links": [
                      {
                        "url": null,
                        "label": "&laquo; Previous",
                        "active": false
                      },
                      {
                        "url": "https://api.biblesupersearch.com/api?page=1",
                        "label": "1",
                        "active": true
                      },
                      {
                        "url": null,
                        "label": "...",
                        "active": false
                      },
                      {
                        "url": "https://api.biblesupersearch.com/api?page=2",
                        "label": "Next &raquo;",
                        "active": false
                      }
                    ],
                    "path": "https://api.biblesupersearch.com/api",
                    "per_page": 30,
                    "to": 30,
                    "total": 420
                  },
                  "errors": [],
                  "error_level": 0,
                  "results": {
                    "kjv": [
                      {
                        "id": 376,
                        "book": 1,
                        "chapter": 15,
                        "verse": 15,
                        "text": "And thou shalt go to thy fathers in peace; thou shalt be buried in a good old age.",
                        "italics": ""
                      },
                      {
                        "id": 613,
                        "book": 1,
                        "chapter": 24,
                        "verse": 21,
                        "text": "And the man wondering at her held his peace, to wit whether the LORD had made his journey prosperous or not.",
                        "italics": ""
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      },
      "Problem": {
        "description": "Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/error"
            },
            "examples": {
              "error": {
                "summary": "error",
                "description": "Response for when the request could not retrieve the specified information.",
                "value": {
                  "hash": "3bucsf74xc",
                  "disambiguation": [],
                  "errors": [
                    "An error messgae about the request and how to fix it."
                  ],
                  "error_level": 4,
                  "results": false
                }
              }
            }
          }
        }
      }
    }
  },
  "x-tagGroups": null
}